# File to set up the radar configuration. 

# Radar signal configuration - for now only FMCW Up-Ramp is supported
minimumFrequencyMhz: 24000
maximumFrequencyMhz: 24750
rampTimeFmcwChirp: 1
# Tx attenuation during measurement
# 0 ~ 0dB, 1 ~ 0.4dB, 2 ~ 0.8dB, 3 ~ 1.4 dB, 4 ~ 2.5dB, 5 ~ 4dB, 6 ~6dB, 7 ~ 9dB
attenuation: 0

# Radar connection configuration
ethernetParams:
  ethernetPort: 1024
  ethernetIp: "192.168.0.2" # IP to connect to the radar with

# Radar signal processing configuration
cfarParams:
  cfarNumGuard: 4
  cfarNumTrainingCells: 10
  cfarThreshold: 4

  # cfarNumGuard: 2
  # cfarNumTrainingCells: 5
  # cfarThreshold: 4
  cfarType: "CASO" # Options are CASO, LEADING_EDGE

# Run configuration
run: RERUN # Options are LIVE, RERUN
sourcePath: "data/Experiment_A/radar" #Experiment_A/radar  Case1/2025-05-02_09-30-00/radar
# Case0/2025-05-02_09-22-44/radar Path to the data to be processed for RERUN mode
#radar/Apr_20_data
recordData: True # Record radar data to disk
recordDataPath: "./output/radar" # Path to the data to be recorded

# How many Radar results to keep in the buffer for analysis and CFAR 
processingWindow: 200

# Print radar runtime settings to console on startup
printSettings: True
