# File to configuration the video processing

# Configuration for the Yolo Processing
# modelWeights: "./yolov8n.pt" # If a path on disk is specified, it will not be downloaded by Yolo
modelWeights: "./yolov8nano.pt" # If a path on disk is specified, it will not be downloaded by Yolo

saveRawImages: True # Determine if the raw images should be saved
saveProcessedVideo: True
outputDirectory: "./output"

# Configration for video source: /dev/video0 is mapped from /dev/video2 on the host

# Use "0" for MS Windows system
videoSource: 0

# use /dev/video0 for "Jetson Orin" or Linux-like system 
#videoSource: "/dev/video0"

#videoSource: "https://youtu.be/LNwODJXcvt4"
#videoSource: "data/Experiment_A/2025_05_05_ExpA_Video_short.mp4"  #data/Experiment_A/2025_05_05_ExpA_Video.mp4

confidenceThreshold: 0.3
iouThreshold: 0.5
videoStream: True

# Configuration for showing the Live Video During Yolo Processing
showBoxesInVideo: True
showVideo: False
printDetectedObjects: False # Print the detected objects in the console as noticed

# Camera Details
cameraHorizontalFOV: 39
cameraZoomFactor: 1.0
imageWidth: 864
imageHeight: 648

videoDelayBetweenProcessingSec: 0.1
